services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            #$dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\WerkstudentBundle\:
        resource: '../../*'
        exclude: '../../{Resources,Migrations}'

    KimaiPlugin\WerkstudentBundle\Repository\WerkSheetRepository:
        class:     KimaiPlugin\WerkstudentBundle\Repository\WerkSheetRepository
        #factory:   ['@doctrine.orm.entity_manager', getRepository]
        factory: ['KimaiPlugin\WerkstudentBundle\Repository\WerkSheetRepository', 'createWerkSheetRepository']
        #arguments: ['App\Entity\Timesheet']